services:
  db:
    image: postgres:17.0
    container_name: db
    environment:
      POSTGRES_DB: "momotova"
      POSTGRES_PASSWORD: inna
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "5430:5432"
    restart: unless-stopped
    networks:
      - inna-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 3 

  inna-app:
    build:
      context: ./
    container_name: inna-app
    networks:
      - inna-net
    depends_on:
      db:
        condition: service_healthy

networks:
  inna-net:
volumes:
  pg-data: